---

- name: copy consul-replicate
  copy:
    src: consul-replicate_0.4.0_linux_amd64.zip
    dest: "{{consul_download_folder}}"

- name: create consul_replicate_dir if it does not exist
  file:
    path: "{{ consul_replicate_dir }}"
    state: directory
    mode: 0755

- name: create replicate dir
  file: path={{ consul_replicate_dir }} state=directory

- name: copy and unpack replicate
  unarchive: >
    src={{ consul_download_folder }}/{{ consul_replicate_archive }}
    dest={{ consul_replicate_dir }}
    copy=no

- name: Clean /tmp/consul-replicate_0.4.0_linux_amd64.zip
  file:
    path: /tmp/consul-replicate_0.4.0_linux_amd64.zip
    state: absent

- name: set ownership
  file: >
    state=directory
    path={{consul_replicate_dir}}
    owner={{consul_user}}
    group={{consul_group}}
    recurse=yes

- name: copy replicate systemd script
  template: >
    src={{consul_replicate_systemd_template}}
    dest=/etc/systemd/system/consul_replicate.service
    owner=root
    group=root
    mode=0644
  when: consul_replicate_use_systemd
  notify:
    - reload systemd
    - restart consul replicate
