---

- name: copy zip
  copy:
    src: zip
    dest: /tmp

- name: Install unzip
  shell: rpm -ivh /tmp/zip/*.rpm
  ignore_errors: yes

- name: Clean /tmp/zip
  file:
    path: /tmp/zip
    state: absent

- name: gather OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_os_family }}.yml"
- include: install.yml
- { include: install-replicate.yml, when: consul_install_consul_replicate }
- { include: install-cli.yml, when: consul_install_consul_cli }
- { include: dnsmasq.yml, when: consul_install_dnsmasq }
- { include: consulate.yml, when: consul_install_consulate }
- service: >
    name=consul
    state="{{ consul_service_state }}"
    enabled=yes
  when: consul_manage_service
- { include: services.yml, when: consul_services is defined and consul_services|length > 0 }
